import type { Component } from "@wibble/core";

export interface RenderToStringResult {
  /** HTML generated by the server renderer. */
  readonly html: string;
  /** Hydration markers emitted for the client runtime. */
  readonly hydration: string;
  /** Asset URLs selected from the optional build manifest. */
  readonly assets: string[];
}

export interface RenderToStringOptions {
  /** Vite-style manifest keyed by entry name. */
  readonly manifest?: Record<string, { file?: string; css?: string[]; assets?: string[] }>;
  /** Manifest entry to collect assets for. */
  readonly entry?: string;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function assetsFor(options: RenderToStringOptions): string[] {
  const entry = options.entry ? options.manifest?.[options.entry] : undefined;
  if (!entry) {
    return [];
  }

  return [entry.file, ...(entry.css ?? []), ...(entry.assets ?? [])].filter((asset): asset is string => Boolean(asset));
}

/** Renders a Wibble component to a conservative HTML string in DOM-capable runtimes. */
export function renderToString<P>(component: Component<P>, props: P, options: RenderToStringOptions = {}): RenderToStringResult {
  const assets = assetsFor(options);
  if (typeof document === "undefined") {
    return {
      html: "<!-- wibble:ssr requires a DOM adapter in this runtime -->",
      hydration: "[]",
      assets
    };
  }

  const container = document.createElement("div");
  const nodes = component(props);
  for (const node of Array.isArray(nodes) ? nodes : [nodes]) {
    container.append(node.cloneNode(true));
  }

  return {
    html: container.innerHTML,
    hydration: escapeHtml(JSON.stringify([])),
    assets
  };
}

/** Marks a container as hydrated; full node reconciliation is a future SSR phase. */
export function hydrate(container: Element, hydration = "[]"): void {
  container.setAttribute("data-wibble-hydrated", "true");
  container.setAttribute("data-wibble-hydration", hydration);
}
